In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import os
from google.colab import drive

drive.mount('/content/drive')
path = '/content/drive/My Drive'

os.chdir(path)
os.listdir(path)

Mounted at /content/drive


['fast-neural-style-pytorch-master',
 'DCGAN-tensorflow-master',
 'CycleGAN-TensorFlow',
 'AnimeGAN',
 '微信图片_20200426165929.jpg',
 '唯尚留学基本信息表-7.29最新版.gdoc',
 '唯尚留学基本信息表-7.29最新版.docx',
 '54logo.png',
 'Eyes_tracking',
 'Cornell Supplemental Essay.gdoc',
 'Personal Statement AdmitSee.gdoc',
 'APA 7th edition template (professional version)（副本）.gdoc',
 'APA 7th edition template (student version)（副本） (1).gdoc',
 'APA 7th edition template (student version)（副本）.gdoc',
 'AP World History, Winter Break Assignment, 2020-2021.docx',
 '张靖烨语文presentation -- 道家 .pptx',
 'EV AP Seminar.gdoc',
 'GreenEnergyPPT.gslides',
 'PopMart视频.mp4',
 'My Movie 15.mp4',
 'epdf.pub_1542591025-5bf113beb7d7bcfa1f27fed1.pdf',
 'COMM Lesson1 .gdoc',
 'Lesson3_Jingye_Zhang.gdoc',
 'Mejo182 Notes.gdoc',
 'ENGL105 Feeder1.1.gdoc',
 'Challenge Statement.gdoc',
 'Project2Samples2021.pdf',
 'Engl105_Project3_Thesis .gdoc',
 'UFO_Data_Analysis',
 'JingyeZhang_portfolio_preparation.zip']

In [2]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 15790895476987034483
 xla_global_id: -1]

In [3]:
ls

sample_data/


/content/drive/My Drive/UFO_Data_Analysis


In [ ]:
from pprint import pprint
from artifici_lda.lda_service import train_lda_pipeline_default


'''FR_STOPWORDS = [
    "le", "les", "la", "un", "de", "en",  # stop words
    "a", "b", "c", "d",  # 1 char words are removed too
    "est", "sur", "tres", "donc", "sont",  # can even mix in some more common words / borderline stop words.
    # even having slang/texto stop words can be good:
    "ya", "pis", "yer"]
# Note: this list of stop words is poor and has been crafted for this example.
'''
FR_STOPWORDS = [","]


fr_comments = concepts

transformed_comments, top_comments, _1_grams, _2_grams = train_lda_pipeline_default(
    fr_comments,
    n_topics=2,
    stopwords=FR_STOPWORDS,
    language='french')
# More languages: 
# ['danish', 'dutch', 'english', 'finnish', 'french', 'german', 'hungarian', 'italian', 
#  'norwegian', 'porter', 'portuguese', 'romanian', 'russian', 'spanish', 'swedish', 'turkish']

pprint(transformed_comments)
pprint(top_comments)
pprint(_1_grams)
pprint(_2_grams)

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("data_with_concepts.csv")

In [3]:
data.dropna(inplace=True)

In [3]:
data.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1        city  \
0           0             0               0                 0  san marcos   
1           3             3               3                 4     kaneohe   
2           6             6               6                 7     norwalk   
3           7             7               7                 8   pell city   
4           8             8               8                 9    live oak   

  state/province country                                        description  \
0             tx      us  This event took place in early fall around 194...   
1             hi      us  AS a Marine 1st Lt. flying an FJ4B fighter att...   
2             ct      us  A bright orange color changing to reddish colo...   
3             al      us  Strobe Lighted disk shape object observed clos...   
4             fl      us  Saucer zaps energy from powerline as my pregna...   

                                            concepts  
0  American Civil War,Baptist,Christianity,Southe...  
1               Close air support,F-35 Lightning II,  
2  Electric power transmission,Orange,Color,Hue,G...  
3                     Birmingham, Alabama,Grid plan,  
4                                  Mother,Pregnancy,

In [4]:
concepts = data['concepts'].tolist()

In [5]:
divided_concepts = []
for concept in concepts:
  concept = concept[:-1]
  for i in range(len(concept.split(","))):
    divided_concepts.append(concept.split(",")[i])
    if i == 2:
      break

In [6]:
len(divided_concepts)

99087

In [12]:
small_concept = divided_concepts[:1500]

In [33]:
small_concept

['American Civil War',
 'Baptist',
 'Christianity',
 'Southern Baptist Convention',
 'Close air support',
 'F-35 Lightning II',
 'Electric power transmission',
 'Orange',
 'Color',
 'Hue',
 'Green',
 'Transmission line',
 'Orange Revolution',
 'Birmingham',
 ' Alabama',
 'Grid plan',
 'Mother',
 'Pregnancy',
 'Western North Carolina',
 'United States',
 'North Carolina',
 'American Civil War',
 'South Carolina',
 'Asheville',
 ' North Carolina',
 'Appalachian State University',
 'Southern United States',
 'Velocity',
 'Oval',
 'Light',
 "Gulliver's Travels",
 'Internal combustion engine',
 'James Brolin',
 'The Lake',
 'Yasmine Bleeth',
 'Linden Ashby',
 'Mark E. Smith',
 'Norah Jones',
 'Fall',
 'South Carolina',
 'Charleston County',
 ' South Carolina',
 "Thomas D'Arcy McGee",
 '1979',
 'Light',
 'Energy',
 'Pennsylvania',
 'Light',
 'Night sky',
 'Sky',
 'Democratic Movement for Change',
 'Israeli legislative election',
 ' 1977',
 'Mulholland Drive',
 'Sky',
 'Pamlico Sound',
 'Cent

In [ ]:
from pprint import pprint
from artifici_lda.lda_service import train_lda_pipeline_default


'''FR_STOPWORDS = [
    "le", "les", "la", "un", "de", "en",  # stop words
    "a", "b", "c", "d",  # 1 char words are removed too
    "est", "sur", "tres", "donc", "sont",  # can even mix in some more common words / borderline stop words.
    # even having slang/texto stop words can be good:
    "ya", "pis", "yer"]
# Note: this list of stop words is poor and has been crafted for this example.
'''
FR_STOPWORDS = [","]


fr_comments = divided_concepts[:1000]

transformed_comments, top_comments, _1_grams, _2_grams = train_lda_pipeline_default(
    fr_comments,
    n_topics=50,
    stopwords=FR_STOPWORDS,
    language='englsh')
# More languages: 
# ['danish', 'dutch', 'english', 'finnish', 'french', 'german', 'hungarian', 'italian', 
#  'norwegian', 'porter', 'portuguese', 'romanian', 'russian', 'spanish', 'swedish', 'turkish']

pprint(transformed_comments)
pprint(top_comments)
pprint(_1_grams)
pprint(_2_grams)

dic = {}
for i in range(len(transformed_comments)):
  comments = transformed_comments[i].tolist()
  index = comments.index(max(comments))
  if top_comments[index] not in dic.keys():
    dic[top_comments[index]] = []
    dic[top_comments[index]].append(small_concept[i])
  else:
    dic[top_comments[index]].append(small_concept[i])
processed_data = pd.DataFrame(dict)
processed_data.to_csv("topic_clustering.csv")

In [ ]:
top_comments

In [ ]:
dic = {}
for i in range(len(transformed_comments)):
  comments = transformed_comments[i].tolist()
  index = comments.index(max(comments))
  if top_comments[index] not in dic.keys():
    dic[top_comments[index]] = []
    dic[top_comments[index]].append(small_concept[i])
  else:
    dic[top_comments[index]].append(small_concept[i])

In [ ]:
for key in dic.keys():
  print(key)
  print(dic[key])

American Hockey League
['American Civil War', 'American Civil War', 'Central America', 'Gulf War', 'Chicago', 'American Hockey League', 'Central Valley', 'North America', 'Premier League', 'Major League Soccer', 'American Civil War', 'Andy Warhol', 'Camera', 'Dimmer', 'American Civil War', 'American Civil War', 'American films', 'Hierarchical query', 'North America', 'Systems of measurement', 'Underwater hockey', 'Ice hockey', 'American Hockey League']
Baptist
['Baptist', 'White tie', 'White', "Visual Art's", ' Oregon', 'White', 'White', 'White', 'Stepfamily', 'White people', 'Ecliptic', "Visual Art's", 'White', "Visual Art's", 'White', 'White dwarf', 'White', 'White', 'Optics', 'White', 'Speed', 'Book of Optics', 'White', 'Visual perception', 'Book of Optics', 'White', 'Book of Optics', 'Ecliptic', 'White', "Visual Art's", 'White', 'White', 'White', ' Oregon', 'Speed', 'White', 'White', 'Speed', 'White', 'Family', 'Book of Optics', 'Oregon', 'White']
City
['Christianity', 'Birmingham'

In [ ]:
data.dropna(inplace=True)

In [13]:
pip install translitcodec

     |████████████████████████████████| 52 kB 906 kB/s 
  Created wheel for translitcodec: filename=translitcodec-0.7.0-py3-none-any.whl size=10152 sha256=0f4b332990d59fd62c9f01d9b0056eb520bbc785aed6bdab2946eb6520ba6f49
  Stored in directory: /root/.cache/pip/wheels/d3/80/ab/6c3e79e264a7234ceb2026d3fafdac65fb5e869eecf67e8263
Successfully built translitcodec


In [14]:
pip install PyStemmer

     |████████████████████████████████| 559 kB 5.2 MB/s 
  Created wheel for PyStemmer: filename=PyStemmer-2.0.1-cp37-cp37m-linux_x86_64.whl size=425705 sha256=a7bdc3f1be2b68c0186971698ba80203432019983a896c9afb3a940bd6828d38
  Stored in directory: /root/.cache/pip/wheels/30/6d/40/0d17a498c5009922dbb3ddaca3d3652387ba94cc96142001f0
Successfully built PyStemmer


In [23]:
pip install lda

     |████████████████████████████████| 351 kB 9.4 MB/s 
     |████████████████████████████████| 99 kB 9.9 MB/s 


In [30]:
import numpy as np
import lda
import lda.datasets
X = lda.datasets.load_reuters()
print(X)
vocab = lda.datasets.load_reuters_vocab()
print("This is vocab " + str(vocab))
titles = lda.datasets.load_reuters_titles()
print("This is title: " + str(titles))
X.shape

X.sum()

model = lda.LDA(n_topics=100, n_iter=1500, random_state=1)
model.fit(X)  # model.fit_transform(X) is also available
topic_word = model.topic_word_  # model.components_ also works
n_top_words = 40
for i, topic_dist in enumerate(topic_word):
  topic_words = np.array(vocab)[np.argsort(topic_dist)][:-(n_top_words+1):-1]
  print('Topic {}: {}'.format(i, ' '.join(topic_words)))

'''
Topic 0: british churchill sale million major letters west britain
Topic 1: church government political country state people party against
Topic 2: elvis king fans presley life concert young death
Topic 3: yeltsin russian russia president kremlin moscow michael operation
Topic 4: pope vatican paul john surgery hospital pontiff rome
Topic 5: family funeral police miami versace cunanan city service
Topic 6: simpson former years court president wife south church
Topic 7: order mother successor election nuns church nirmala head
Topic 8: charles prince diana royal king queen parker bowles
Topic 9: film french france against bardot paris poster animal
Topic 10: germany german war nazi letter christian book jews
Topic 11: east peace prize award timor quebec belo leader
Topic 12: n't life show told very love television father
Topic 13: years year time last church world people say
Topic 14: mother teresa heart calcutta charity nun hospital missionaries
Topic 15: city salonika capital buddhist cultural vietnam byzantine show
Topic 16: music tour opera singer israel people film israeli
Topic 17: church catholic bernardin cardinal bishop wright death cancer
Topic 18: harriman clinton u.s ambassador paris president churchill france
Topic 19: city museum art exhibition century million churches set'''

INFO:lda:n_documents: 395
INFO:lda:vocab_size: 4258
INFO:lda:n_words: 84010
INFO:lda:n_topics: 100
INFO:lda:n_iter: 1500


[[1 0 1 ... 0 0 0]
 [7 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]]
This is vocab ('church', 'pope', 'years', 'people', 'mother', 'last', 'told', 'first', 'world', 'year', 'president', 'teresa', 'charles', 'catholic', 'during', 'life', 'u.s', 'city', 'public', 'time', 'since', 'family', 'king', 'former', 'british', 'harriman', 'against', 'country', 'vatican', 'made', 'three', 'hospital', 'minister', 'home', 'died', 'tuesday', 'government', "n't", 'million', 'prince', 'john', 'very', 'war', 'say', 'order', 'day', 'political', 'leader', 'heart', 'roman', 'yeltsin', 'later', 'france', 'party', 'monday', 'death', 'clinton', 'sunday', 'elvis', 'state', 'diana', 'royal', 'wednesday', 'churchill', 'official', 'service', 'including', 'film', 'while', 'week', 'left', 'work', 'paris', 'around', 'american', 'saying', 'take', 'doctors', 'group', 'son', 'queen', 'house', 'police', 'national', 'under', 'surgery', 'next', 'peace', 'paul', 'long', 'c

INFO:lda:<0> log likelihood: -1258788
INFO:lda:<10> log likelihood: -734487
INFO:lda:<20> log likelihood: -708068
INFO:lda:<30> log likelihood: -698147
INFO:lda:<40> log likelihood: -691363
INFO:lda:<50> log likelihood: -687491
INFO:lda:<60> log likelihood: -684165
INFO:lda:<70> log likelihood: -682336
INFO:lda:<80> log likelihood: -680400
INFO:lda:<90> log likelihood: -678905
INFO:lda:<100> log likelihood: -676797
INFO:lda:<110> log likelihood: -675647
INFO:lda:<120> log likelihood: -675180
INFO:lda:<130> log likelihood: -674108
INFO:lda:<140> log likelihood: -673157
INFO:lda:<150> log likelihood: -673066
INFO:lda:<160> log likelihood: -672008
INFO:lda:<170> log likelihood: -671173
INFO:lda:<180> log likelihood: -671111
INFO:lda:<190> log likelihood: -670026
INFO:lda:<200> log likelihood: -669592
INFO:lda:<210> log likelihood: -668796
INFO:lda:<220> log likelihood: -668897
INFO:lda:<230> log likelihood: -668898
INFO:lda:<240> log likelihood: -668443
INFO:lda:<250> log likelihood: -668

Topic 0: buddhist vietnam cancer national friday local dent ceremony organisation former monks law temple town die 1975 prostate earlier diagnosed hanoi senior end australia war sunday city buddhism helping effect territory banned south thien hao front followed generous increasingly frequent thich
Topic 1: christmas year state days day time church held almost castro cuba first despite foreign residence eve trees especially cancelled 24 experience stores december suffered special certainly third long spend season gorbachev period embassy message fast meeting efforts spokesman authorities reminded
Topic 2: social party major leader leadership beetham credit since redwood chairman movement former 1995 john died election 1986 third prominent union 1990 campaigner alliance end mp democrat saturday rangitikei 1980 worked forward challenge board mayor took 1972 conservatives favourite veteran battle
Topic 3: people n't own years world added end right while know made very came big does says th

"\nTopic 0: british churchill sale million major letters west britain\nTopic 1: church government political country state people party against\nTopic 2: elvis king fans presley life concert young death\nTopic 3: yeltsin russian russia president kremlin moscow michael operation\nTopic 4: pope vatican paul john surgery hospital pontiff rome\nTopic 5: family funeral police miami versace cunanan city service\nTopic 6: simpson former years court president wife south church\nTopic 7: order mother successor election nuns church nirmala head\nTopic 8: charles prince diana royal king queen parker bowles\nTopic 9: film french france against bardot paris poster animal\nTopic 10: germany german war nazi letter christian book jews\nTopic 11: east peace prize award timor quebec belo leader\nTopic 12: n't life show told very love television father\nTopic 13: years year time last church world people say\nTopic 14: mother teresa heart calcutta charity nun hospital missionaries\nTopic 15: city salonika 

In [19]:
rm -r /tmp/

In [8]:
import os
os.environ['JOBLIB_TEMP_FOLDER'] = '/tmp'